//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvigilonAlarmDemoApp.DataAccesslayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AvigilonAlarmDemoAppDataLayerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvigilonAlarmDemoAppDataLayerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvigilonAlarmDemoApp.DataAccesslayer.AvigilonAlarmDemoAppDataLayerResource", typeof(AvigilonAlarmDemoAppDataLayerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alarms.
        /// </summary>
        internal static string AlarmsPath {
            get {
                return ResourceManager.GetString("AlarmsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alarm.
        /// </summary>
        internal static string AlarmUpdatePath {
            get {
                return ResourceManager.GetString("AlarmUpdatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cameras.
        /// </summary>
        internal static string CamerasPath {
            get {
                return ResourceManager.GetString("CamerasPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json; charset=utf-8.
        /// </summary>
        internal static string HttpContentType {
            get {
                return ResourceManager.GetString("HttpContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string LoginPath {
            get {
                return ResourceManager.GetString("LoginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        internal static string LogoutPath {
            get {
                return ResourceManager.GetString("LogoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session=.
        /// </summary>
        internal static string SessionQuery {
            get {
                return ResourceManager.GetString("SessionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sites.
        /// </summary>
        internal static string SitePath {
            get {
                return ResourceManager.GetString("SitePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string UrlQuery {
            get {
                return ResourceManager.GetString("UrlQuery", resourceCulture);
            }
        }
    }
}
